- platform: unifi
  host: 192.168.0.10
  port: 8443
  verify_ssl: false
  username: !secret unifi_user
  password: !secret unifi_pass
  interval_seconds: 30
  track_new_devices: true
  
- platform: snmp
  host: 192.168.0.1
  community: DougRO
  baseoid: 1.3.6.1.2.1.4.22.1.2

- platform: trackr
  username: trackr_user
  password: trackr_pass
